### ISSUE TITLE
ACMEv2 - Domain with Cyrillic alphabet

### ISSUE THREAD

**Issue by asapostolov** [ohadschn/letsencrypt-webapp-renewer#104]
Hey!

So, I'm upgrading from version `0.9.6` to `1.0.5` because of the ACMEv2 support. I use the same websites configuration, just change the .zip - and the exception below occurs.

`Cannot issue for "??-????.com": Domain name contains an invalid character`

The domain name is `пм-атра.com`. Contains Cyrillic alphabet characters. This issue is realted to #41 and [#199](https://github.com/sjkp/letsencrypt-siteextension/issues/199) which were resolved some time ago.

Do you think the issue is again in the underlying library [letsencrypt-siteextension](https://github.com/sjkp/letsencrypt-siteextension)? Any idea how to fix it?

```
[06/01/2020 15:23:34 > f0c9b0: ERR ] Unhandled Exception: System.AggregateException: Encountered exception(s) during cert renewal (and/or notification) ---> Certes.AcmeRequestException: Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/finalize/70771399/3591785838'.
[06/01/2020 15:23:34 > f0c9b0: ERR ] urn:ietf:params:acme:error:rejectedIdentifier: Error finalizing order :: Cannot issue for "??-????.com": Domain name contains an invalid character
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at Certes.Acme.IAcmeHttpClientExtensions.<Post>d__0`1.MoveNext()
[06/01/2020 15:23:34 > f0c9b0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at Certes.Acme.OrderContext.<Finalize>d__2.MoveNext()
[06/01/2020 15:23:34 > f0c9b0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at Certes.IOrderContextExtensions.<Finalize>d__0.MoveNext()
[06/01/2020 15:23:34 > f0c9b0: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2020 15:23:34 > f0c9b0: ERR ]    at Certes.IOrderContextExtensions.<Generate>d__2.MoveNext()
````

**Comment by ohadschn** [comment]
Could you share the full execution log which should include the full config and the full exception including stack trace (feel free to scrub out PII)?

**Comment by asapostolov** [comment]
Thank you! Here is a gist of with the [WebJob Log](https://gist.github.com/asapostolov/91a7f724e60883a3adcd3d7295482244)

**Comment by ohadschn** [comment]
Funny story, I ran into the exact same issue ~8 months ago, reported it, and found a workaround: https://github.com/sjkp/letsencrypt-siteextension/issues/340

Sorry for my memory malfunction...

**Comment by asapostolov** [comment]
Can you clarify, how the workaround looks like when I make the configuration in the webApp? Is `letsencrypt:Hostnames` equivalent to `letsencrypt:webAppName-hosts`? Can you give an example?

**Comment by ohadschn** [comment]
Yes that is the equivalent. The sample from the docs should work:
`letsencrypt:ohadsoft-hosts`: `www.ohadsoft.com;ohadsoft.com;myümlautdomain.de`

**Comment by asapostolov** [comment]
Thank you, it worked!

**Comment by ohadschn** [comment]
Re-opening as I consider this only a workaround
