### ISSUE TITLE
Unabled [sic] to create Azure Web Site Management client

### ISSUE THREAD

**Issue by MatthewSteeples** [ohadschn/letsencrypt-webapp-renewer#6]
Receiving this error when the WebJob is running. I'm running the latest code (from master) commit 611773f so I'm wondering if something has broken since the last release (I see a lot of dependencies had changed)

It's happening after "Deleting answer" (which is after the existence of the files has been verified by the Let's Encrypt service).

> AzureLetsEncryptRenewer.exe Error: 0 : Unabled to create Azure Web Site Management client System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ACMESharp.PKI.CertificateProvider.GetProvider(String name, IReadOnlyDictionary`2 initParams)
   at LetsEncrypt.Azure.Core.Services.AcmeService.GetCertificate(AcmeClient client)
   at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__10.MoveNext()
ERROR: Encountered exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ACMESharp.PKI.CertificateProvider.GetProvider(String name, IReadOnlyDictionary`2 initParams)
   at LetsEncrypt.Azure.Core.Services.AcmeService.GetCertificate(AcmeClient client)
   at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.RequestAndInstallInternal(IAcmeConfig config)
   at LetsEncrypt.Azure.Core.CertificateManager.AddCertificate()
   at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.Renew(RenewalParameters renewParams) in d:\a\1\s\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 53
   at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.Renew() in d:\a\1\s\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 31

**Comment by ohadschn** [comment]
Since you built it yourself, I'm guessing this is the issue (as it happened to me too):

https://github.com/ebekker/ACMESharp/issues/216#issuecomment-317200486

**Comment by MatthewSteeples** [comment]
@ohadschn Yep, that looks to have fixed it. Adding the dependency on BouncyCastle and removing OpenSSL got me to the next step. It now fails when saving the .pfx but that's a different error!

**Comment by ohadschn** [comment]
Actually what I meant was doing this: https://github.com/ebekker/ACMESharp/issues/216#issuecomment-281977202. When I update the [letsencrypt.azure.core](https://www.nuget.org/packages/letsencrypt.azure.core/) dependency it will be using `BouncyCastle` like you mentioned and these issues should go away.

**Comment by MatthewSteeples** [comment]
I updated the dependencies on my own fork to deploy (as I'm just experimenting currently so not expecting a stable release) and got past most of the certificate generation issues. I now get a failure (but no Exception) when trying to save the .pfx file so I'll probably hold out for the next official releases of the dependencies before trying again. I've written a Powershell add-in for ACMESharp that will allow us to use DNS auth with DNSMadeEasy so I'm not in a massive rush for this, just thought I'd try and help out where I could

**Comment by ohadschn** [comment]
Sounds good. Would you mind sharing the error you're getting so I have a heads up for when I update the dependencies?

**Comment by MatthewSteeples** [comment]
Sure

> [10/08/2017 20:37:34 > 4c3b89: INFO]  Saving Certificate to D:\home\siteextensions\letsencrypt\config\httpsacme-v01.api.letsencrypt.org\beta.ledgerscope.com-all.pfx
> [10/08/2017 20:37:34 > 4c3b89: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Saving Certificate to D:\home\siteextensions\letsencrypt\config\httpsacme-v01.api.letsencrypt.org\beta.ledgerscope.com-all.pfx
> [10/08/2017 20:37:34 > 4c3b89: SYS INFO] Status changed to Failed
> [10/08/2017 20:37:34 > 4c3b89: SYS ERR ] Job failed due to exit code -1073740940

The only thing I've been able to find out is that for some reason the pfx isn't getting saved, and that error looks to be some form of filesystem issue

**Comment by ohadschn** [comment]
Have you tried creating a file with the same name in manually the Kudu console? You can find it at `https://FOO.scm.azurewebsites.net/DebugConsole` where FOO is the name of your site.

**Comment by MatthewSteeples** [comment]
I wasn't quite correct earlier. A .pfx file has been created (according to the filesystem) but it is 0 bytes in size. Not sure how that helps the debugging!

**Comment by MatthewSteeples** [comment]
(and I can delete / re-create a pfx file in that folder through the console)

**Comment by ohadschn** [comment]
So clearly the last trace you're seeing is coming from [this line](https://github.com/sjkp/letsencrypt-siteextension/blob/b3114acfe62654a655ffa55ef425d24f44ff3055/LetsEncrypt.SiteExtension.Core/Services/ACMEService.cs#L251). I'm not sure exactly what binary you're running but that part of the source hasn't changed for a while which is weird for two reasons

1. If you say the file was created, presumably that means the file stream was opened successfully so I would expect any error during the cert export to be caught by the `catch` block there and therefore trace the exact error. 
2. The error code your webjob is getting implies a [heap corruption](https://social.microsoft.com/Forums/en-US/6237ab2f-a4c3-47ea-9e90-652dc63081fd/exit-code-1073740940?forum=windowshpcdevs). Interestingly, [This SO thread](https://stackoverflow.com/questions/32606590/azure-webjob-failing-exit-code-1073740940) mentions the same exit code and it too deals with certificates in WebJobs.

The latter thread suggested his executable ran fine on his local machine. Could you try that out?
