### ISSUE TITLE
First run always errors always

### ISSUE THREAD

**Issue by Jogai** [ohadschn/letsencrypt-webapp-renewer#78]
It seems to me that the first run will always error out. 

What I did was:

1. Run with 1 group configured: 2 minutes running => failed
2. Run without changing anything: 28 seconds running => succes
3. Run with 8 other groups enabled: 3 minutes running => success

I'm pasting the error below, but I'm not sure it will help because runs right after the first fail tend to succeed. It has something to do with that first run, but I cant think of a reason.

```
[05/11/2019 06:46:21 > bcf09c: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Answer should now be browsable at http://www.example.com/.well-known/acme-challenge/Jw29L6qSjgSTXje4ggI_GzV0jRH2i1EVRS-zX2eaF-o
[05/11/2019 06:48:02 > bcf09c: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Encountered exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__16.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__17.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__12.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<RenewCore>d__7.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 75
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 34
[05/11/2019 06:48:02 > bcf09c: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Unexpected exception: System.AggregateException: Encountered exception(s) during cert renewal (and/or notification) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__16.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__17.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__12.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<RenewCore>d__7.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 75
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 34
[05/11/2019 06:48:02 > bcf09c: INFO]    --- End of inner exception stack trace ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 46
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.Program.WebJobMain(String webjobName) in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\Program.cs:line 55
[05/11/2019 06:48:02 > bcf09c: INFO] ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__16.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__17.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__12.MoveNext()
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<RenewCore>d__7.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 75
[05/11/2019 06:48:02 > bcf09c: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 34<---
[05/11/2019 06:48:02 > bcf09c: INFO] 
[05/11/2019 06:48:02 > bcf09c: ERR ] 
[05/11/2019 06:48:02 > bcf09c: ERR ] Unhandled Exception: System.AggregateException: Encountered exception(s) during cert renewal (and/or notification) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: ERR ]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[05/11/2019 06:48:02 > bcf09c: ERR ]    at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: ERR ]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: ERR ]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__16.MoveNext()
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: ERR ]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__17.MoveNext()
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/11/2019 06:48:02 > bcf09c: ERR ]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__12.MoveNext()
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<RenewCore>d__7.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 75
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 34
[05/11/2019 06:48:02 > bcf09c: ERR ]    --- End of inner exception stack trace ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 46
[05/11/2019 06:48:02 > bcf09c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/11/2019 06:48:02 > bcf09c: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.Program.WebJobMain(String webjobName) in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\Program.cs:line 60
[05/11/2019 06:48:02 > bcf09c: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.Program.Main(String[] args) in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\Program.cs:line 35
[05/11/2019 06:48:02 > bcf09c: SYS INFO] Status changed to Failed
[05/11/2019 06:48:02 > bcf09c: SYS ERR ] Job failed due to exit code -532462766

**Comment by ohadschn** [comment]
This is the issue you are facing:
https://github.com/sjkp/letsencrypt-siteextension/issues/277
https://github.com/sjkp/letsencrypt-siteextension/issues/166

Quoting Simon:

> This error happens when the extension is unable to request the challenge file successfully. After the extension has written the challenge file to disk, it tries to request it the same way that letsencrypt would, and for some reason your site fails to respond to that request [...] I would encourage you to check if you can browse the challenge file yourself, from the .well-known/acme-challenge/ folder.

Simon added retries, which might have helped your case (Seeing as subsequent attempts succeed),, but unfortunately he did so in a fashion that doesn't catch this specific error. I've opened an issue on his repository : https://github.com/sjkp/letsencrypt-siteextension/issues/312.
